function reg = registry()
% registry  Problem registry with IDs, names, and default dimensions.
%   Returns an array of structs with fields: id, name, n, m.

reg = struct( ...
    'id',  {1, 2, 5, 6, 10}, ...
    'name',{'P1','P2','P5','P6','P10'}, ...
    'n',   {2, 4, 2, 2, 10}, ...
    'm',   {2, 2, 2, 2, 2} ...
);

end

