function s = latex_escape(s)
% utils.latex_escape  Escape common LaTeX special characters in a string.
if isempty(s), return; end
repl = { ...
  {'\', '\textbackslash{}'}; ...
  {'%', '\%'}; ...
  {'_', '\_'}; ...
  {'{', '\{'}; ...
  {'}', '\}'}; ...
  {'#', '\#'}; ...
  {'&', '\&'}; ...
  {'$', '\$'}; ...
  {'~', '\textasciitilde{}'}; ...
  {'^', '\textasciicircum{}'} ...
};
for i = 1:numel(repl)
  s = strrep(s, repl{i}{1}, repl{i}{2});
end
end

